# Generated by Django 5.0.6 on 2024-06-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='store_product',
        ),
    ]
