# Generated by Django 5.0.6 on 2024-06-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
